//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibararyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public System.DateTime ExpectedDate { get; set; }
    }
}
